import { AosInit } from "@/components/aos-init";
import { CartProvider } from "@/contexts/CartContext";
import { SearchProvider } from "@/contexts/SearchContext";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Kodchasan } from "next/font/google";
import "../styles/globals.css";

const kodchasan = Kodchasan({
  weight: "400",
  variable: "--font-kodchasan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Little Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kodchasan.className} antialiased`}>
        <CartProvider>
          <SearchProvider>
            <SessionProvider>{children}</SessionProvider>
            <AosInit />
          </SearchProvider>
        </CartProvider>
      </body>
    </html>
  );
}
