import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/data/contexts/CartContext";

const kodchasan = Kodchasan({
  weight: "400",
  variable: "--font-kodchasan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Little Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kodchasan.className} antialiased`}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
